# Generated by Django 6.0.2 on 2026-02-28 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('siglas', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Siglas')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Teléfono')),
                ('cuenta_bancaria', models.CharField(max_length=16, unique=True, verbose_name='Cuenta bancaria')),
                ('codigo_REEUP', models.CharField(max_length=11, unique=True, verbose_name='Código REEUP')),
                ('NIT', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(max_length=300, unique=True, verbose_name='Dirección')),
                ('geolocalizacion', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Geolocalización (lat,lon)')),
                ('ruta_documento_contrato_electrico', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ruta del contrato eléctrico')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo_DPA', models.CharField(max_length=2, verbose_name='Código DPA')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='NAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Código (4 dígitos)')),
                ('actividad', models.TextField(verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'NAE',
                'verbose_name_plural': 'NAE',
            },
        ),
        migrations.CreateModel(
            name='OACE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('siglas', models.CharField(max_length=20, unique=True, verbose_name='Siglas')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('direccion_sede_principal', models.CharField(blank=True, max_length=300, verbose_name='Dirección sede principal')),
                ('telefono_sede_principal', models.CharField(blank=True, max_length=20, verbose_name='Teléfono sede principal')),
            ],
            options={
                'verbose_name': 'OACE',
                'verbose_name_plural': 'OACE',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo_DPA', models.IntegerField(unique=True, verbose_name='Código DPA')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Sector_economico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sector económico',
                'verbose_name_plural': 'Sectores económicos',
            },
        ),
        migrations.CreateModel(
            name='Unidad_medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('unidad', models.CharField(max_length=20, unique=True, verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
        migrations.CreateModel(
            name='Entidad_empresarial',
            fields=[
                ('entidad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_gestion.entidad')),
            ],
            options={
                'verbose_name': 'Entidad empresarial',
                'verbose_name_plural': 'Entidades empresariales',
            },
            bases=('app_gestion.entidad',),
        ),
        migrations.CreateModel(
            name='Entidad_presupuestada',
            fields=[
                ('entidad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_gestion.entidad')),
            ],
            options={
                'verbose_name': 'Entidad presupuestada',
                'verbose_name_plural': 'Entidades presupuestadas',
            },
            bases=('app_gestion.entidad',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('apellido2', models.CharField(blank=True, max_length=50, verbose_name='Segundo apellido')),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('entidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='app_gestion.entidad', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
        ),
        migrations.AddField(
            model_name='entidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='app_gestion.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='nae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='app_gestion.nae', verbose_name='NAE'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='oace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='app_gestion.oace', verbose_name='OACE (si pertenece a OACE)'),
        ),
        migrations.CreateModel(
            name='OSDE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('siglas', models.CharField(max_length=20, unique=True, verbose_name='Siglas')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('direccion_sede_principal', models.CharField(blank=True, max_length=300, verbose_name='Dirección sede principal')),
                ('telefono_sede_principal', models.CharField(blank=True, max_length=20, verbose_name='Teléfono sede principal')),
                ('oace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='osdes', to='app_gestion.oace', verbose_name='OACE que atiende')),
            ],
            options={
                'verbose_name': 'OSDE',
                'verbose_name_plural': 'OSDE',
            },
        ),
        migrations.AddField(
            model_name='entidad',
            name='osde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='app_gestion.osde', verbose_name='OSDE (si pertenece a OSDE)'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='app_gestion.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='sector_economico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='app_gestion.sector_economico', verbose_name='Sector económico'),
        ),
        migrations.CreateModel(
            name='Servicio_electrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('codigo_servicio', models.IntegerField(unique=True, verbose_name='Código de servicio')),
                ('tarifa_contratada', models.FloatField(verbose_name='Tarifa contratada')),
                ('demanda_contratada', models.FloatField(verbose_name='Demanda contratada')),
                ('regimen_trabajo', models.IntegerField(verbose_name='Régimen de trabajo')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_electricos', to='app_gestion.entidad', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Servicio eléctrico',
                'verbose_name_plural': 'Servicios eléctricos',
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=300, unique=True, verbose_name='Dirección')),
                ('geolocalizacion', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Geolocalización (lat,lon)')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establecimientos', to='app_gestion.municipio', verbose_name='Municipio')),
                ('servicio_electrico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='app_gestion.servicio_electrico', verbose_name='Servicio eléctrico')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
            },
        ),
        migrations.CreateModel(
            name='Portador_energetico_elec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('consumo_planificado', models.FloatField(blank=True, null=True, verbose_name='Consumo planificado')),
                ('consumo_real', models.FloatField(verbose_name='Consumo real')),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portadores', to='app_gestion.servicio_electrico', verbose_name='Servicio eléctrico')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portadores', to='app_gestion.unidad_medida', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Portador energético de electricidad',
                'verbose_name_plural': 'Portadores energéticos de electricidad',
            },
        ),
        migrations.AddConstraint(
            model_name='municipio',
            constraint=models.UniqueConstraint(fields=('provincia', 'codigo_DPA'), name='unique_municipio_por_provincia'),
        ),
        migrations.AlterUniqueTogether(
            name='portador_energetico_elec',
            unique_together={('servicio', 'año', 'mes')},
        ),
    ]
