# Generated by Django 6.0.2 on 2026-04-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('siglas', models.CharField(blank=True, max_length=20, null=True, verbose_name='Siglas')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=16, null=True, verbose_name='Cuenta bancaria')),
                ('codigo_REEUP', models.CharField(max_length=11, unique=True, verbose_name='Código REEUP')),
                ('NIT', models.CharField(blank=True, max_length=11, null=True, verbose_name='NIT')),
                ('direccion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección')),
                ('geolocalizacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Geolocalización (lat,lon)')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo_DPA', models.CharField(max_length=2, verbose_name='Código DPA')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='NAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Código (4 dígitos)')),
                ('actividad', models.TextField(verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'NAE',
                'verbose_name_plural': 'NAE',
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('siglas', models.CharField(max_length=20, verbose_name='Siglas')),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='Código de organismo')),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo_DPA', models.IntegerField(unique=True, verbose_name='Código DPA')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Entidad_empresarial',
            fields=[
                ('entidad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_gestion.entidad')),
            ],
            options={
                'verbose_name': 'Entidad empresarial',
                'verbose_name_plural': 'Entidades empresariales',
            },
            bases=('app_gestion.entidad',),
        ),
        migrations.CreateModel(
            name='Entidad_presupuestada',
            fields=[
                ('entidad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_gestion.entidad')),
            ],
            options={
                'verbose_name': 'Entidad presupuestada',
                'verbose_name_plural': 'Entidades presupuestadas',
            },
            bases=('app_gestion.entidad',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('apellido2', models.CharField(blank=True, max_length=50, verbose_name='Segundo apellido')),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('entidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='app_gestion.entidad', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
        ),
        migrations.AddField(
            model_name='entidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='app_gestion.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='nae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='app_gestion.nae', verbose_name='NAE'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='app_gestion.provincia', verbose_name='Provincia'),
        ),
        migrations.CreateModel(
            name='Servicio_electrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('codigo_servicio', models.IntegerField(verbose_name='Código de servicio')),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('consumo_real', models.FloatField(verbose_name='Consumo real')),
                ('tarifa_contratada', models.CharField(verbose_name='Tarifa contratada')),
                ('demanda_contratada', models.FloatField(verbose_name='Demanda contratada')),
                ('regimen_trabajo', models.IntegerField(verbose_name='Régimen de trabajo')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_electricos', to='app_gestion.entidad', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Servicio eléctrico',
                'verbose_name_plural': 'Servicios eléctricos',
            },
        ),
        migrations.AddConstraint(
            model_name='municipio',
            constraint=models.UniqueConstraint(fields=('provincia', 'codigo_DPA'), name='unique_municipio_por_provincia'),
        ),
        migrations.AddConstraint(
            model_name='servicio_electrico',
            constraint=models.UniqueConstraint(fields=('codigo_servicio', 'mes', 'año'), name='unique_servicio_mes_año'),
        ),
    ]
