# Generated by Django 6.0.2 on 2026-03-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Dirección'),
        ),
    ]
