# Generated by Django 6.0.2 on 2026-05-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad_presupuestada',
            name='entidad_ptr',
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AddField(
            model_name='entidad',
            name='tipo',
            field=models.CharField(choices=[('presupuestada', 'Presupuestada'), ('empresarial', 'Empresarial')], db_index=True, default='presupuestada', max_length=20, verbose_name='Tipo de entidad'),
        ),
        migrations.DeleteModel(
            name='Entidad_empresarial',
        ),
        migrations.DeleteModel(
            name='Entidad_presupuestada',
        ),
    ]
