# Generated by Django 6.0.2 on 2026-03-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0002_alter_entidad_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Cuenta bancaria'),
        ),
    ]
