# Generated by Django 6.0.2 on 2026-05-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0002_remove_entidad_presupuestada_entidad_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_electrico',
            name='regimen_trabajo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Régimen de trabajo'),
        ),
    ]
