# Generated by Django 6.0.2 on 2026-03-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0003_alter_entidad_cuenta_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='NIT',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Cuenta bancaria'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='geolocalizacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Geolocalización (lat,lon)'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='ruta_documento_contrato_electrico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta del contrato eléctrico'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='siglas',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
