# Generated by Django 6.0.2 on 2026-03-07 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0004_alter_entidad_nit_alter_entidad_cuenta_bancaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='nae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='app_gestion.nae', verbose_name='NAE'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='sector_economico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='app_gestion.sector_economico', verbose_name='Sector económico'),
        ),
    ]
