# Generated by Django 6.0.2 on 2026-03-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0005_alter_entidad_nae_alter_entidad_sector_economico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_electrico',
            name='tarifa_contratada',
            field=models.CharField(verbose_name='Tarifa contratada'),
        ),
    ]
