# Generated by Django 6.0.2 on 2026-03-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0006_alter_servicio_electrico_tarifa_contratada'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='portador_energetico_elec',
            index=models.Index(fields=['año'], name='app_gestion_año_808ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='portador_energetico_elec',
            index=models.Index(fields=['mes'], name='app_gestion_mes_d90d95_idx'),
        ),
        migrations.AddIndex(
            model_name='portador_energetico_elec',
            index=models.Index(fields=['año', 'mes'], name='app_gestion_año_754bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='portador_energetico_elec',
            index=models.Index(fields=['servicio', 'año', 'mes'], name='app_gestion_servici_e90f07_idx'),
        ),
    ]
