# Generated by Django 6.0.2 on 2026-03-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0007_portador_energetico_elec_app_gestion_año_808ad1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oace',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='oace',
            name='direccion_sede_principal',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección sede principal'),
        ),
        migrations.AlterField(
            model_name='oace',
            name='telefono_sede_principal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono sede principal'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='direccion_sede_principal',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección sede principal'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='telefono_sede_principal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono sede principal'),
        ),
    ]
