# Generated by Django 6.0.2 on 2026-04-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0008_alter_oace_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('siglas', models.CharField(max_length=20, unique=True, verbose_name='Siglas')),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='Código de organismo')),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
            },
        ),
        migrations.RemoveField(
            model_name='osde',
            name='oace',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='oace',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='osde',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='ruta_documento_contrato_electrico',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='sector_economico',
        ),
        migrations.DeleteModel(
            name='OACE',
        ),
        migrations.DeleteModel(
            name='OSDE',
        ),
    ]
