# Generated by Django 6.0.2 on 2026-04-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0009_organismo_remove_osde_oace_remove_entidad_oace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='siglas',
            field=models.CharField(max_length=20, verbose_name='Siglas'),
        ),
    ]
