# Generated by Django 6.0.2 on 2026-04-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0010_alter_organismo_siglas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portador_energetico_elec',
            name='unidad_medida',
        ),
        migrations.DeleteModel(
            name='Unidad_medida',
        ),
    ]
