# Generated by Django 6.0.2 on 2026-04-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0011_remove_portador_energetico_elec_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
