# Generated by Django 6.0.2 on 2026-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0012_alter_entidad_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio_electrico',
            name='entidad',
        ),
        migrations.AddField(
            model_name='servicio_electrico',
            name='entidades',
            field=models.ManyToManyField(related_name='servicios_electricos', to='app_gestion.entidad', verbose_name='Entidades'),
        ),
    ]
