# Generated by Django 6.0.2 on 2026-04-17 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0013_remove_servicio_electrico_entidad_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portador_energetico_elec',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='portador_energetico_elec',
            name='app_gestion_año_808ad1_idx',
        ),
        migrations.RemoveIndex(
            model_name='portador_energetico_elec',
            name='app_gestion_mes_d90d95_idx',
        ),
        migrations.RemoveIndex(
            model_name='portador_energetico_elec',
            name='app_gestion_año_754bb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='portador_energetico_elec',
            name='app_gestion_servici_e90f07_idx',
        ),
        migrations.RemoveField(
            model_name='servicio_electrico',
            name='entidades',
        ),
        migrations.AddField(
            model_name='servicio_electrico',
            name='año',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio_electrico',
            name='consumo_real',
            field=models.FloatField(default=1, verbose_name='Consumo real'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio_electrico',
            name='entidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_electricos', to='app_gestion.entidad', verbose_name='Entidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio_electrico',
            name='mes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio_electrico',
            name='codigo_servicio',
            field=models.IntegerField(verbose_name='Código de servicio'),
        ),
        migrations.AddConstraint(
            model_name='servicio_electrico',
            constraint=models.UniqueConstraint(fields=('codigo_servicio', 'mes', 'año'), name='unique_servicio_mes_año'),
        ),
        migrations.DeleteModel(
            name='Portador_energetico_elec',
        ),
    ]
